profile_id=1.20.1
selector_key=mc_1_20_1
status=build-ready-legacy-backport
build_ready=true

minecraft_version=1.20.1
minecraft_dependency=1.20.1
java_version=17

mappings_mode=yarn
yarn_mappings=1.20.1+build.10

loader_version=0.15.11
loader_dependency=>=0.15.11
fabric_api_version=0.92.2+1.20.1
carpet_core_version=1.20-1.4.112+v230608
