plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.11'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

def resourceProperties = [
        version: version.toString(),
        minecraft_dependency: "~${minecraft_version}",
        loader_dependency: ">=${loader_version}",
        fabric_api_dependency: ">=${fabric_version}",
        carpet_dependency: ">=${carpet_core_version}",
        target_profile: minecraft_version.toString()
]
def licenseArchiveName = archives_base_name.toString()

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
    maven { url = 'https://masa.dy.fi/maven' }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    implementation "carpet:fabric-carpet:${project.carpet_core_version}"
    testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
}

loom {
    splitEnvironmentSourceSets()
}

fabricApi {
    configureTests {
        createSourceSet = true
        modId = "carpetlir-gametest"
        enableGameTests = true
        enableClientGameTests = false
        eula = true
    }
}

processResources {
    inputs.properties resourceProperties

    filesMatching('fabric.mod.json') {
        expand resourceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
    it.options.encoding = 'UTF-8'
    it.options.compilerArgs.add('-Xlint:deprecation')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

test {
    useJUnitPlatform()
}

jar {
    from('LICENSE') {
        rename { "${it}_${licenseArchiveName}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
}
