org.gradle.jvmargs=-Xmx2G

minecraft_version=1.14.4
yarn_mappings=1.14.4+build.16
loader_version=0.10.5+build.213
fabric_version=0.28.5+1.14
carpet_version=1.14.4-1.3.7+v200127
carpet_mod_version=1.3.7

mod_version=1.0.3-classic.1
maven_group=org.lavro
archives_base_name=carpet-lir-addition-mc1.14.4
