minecraft_version=26.1.1
minecraft_dependency=26.1.1
archive_minecraft_label=26.1.1
loader_version=0.19.3
fabric_api_version=0.145.4+26.1.1
carpet_core_version=26.1+v260401
loom_version=1.17.11
source_family=mojang-26
java_version=25
mappings_mode=mojang
