profile_id=1.20.2
selector_key=mc_1_20_2
status=build-ready-intermediate
build_ready=true

minecraft_version=1.20.2
minecraft_dependency=1.20.2
java_version=17

mappings_mode=yarn
yarn_mappings=1.20.2+build.4

loader_version=0.15.11
loader_dependency=>=0.15.11
fabric_api_version=0.91.6+1.20.2
carpet_core_version=1.20.2-1.4.119+v230928

recipe_format=1.20.1
source_overlay=1.20.2
include_shared_modern=false
